# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  issues:
    types: [opened]


jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Assign label based on issue title
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const github = require('@actions/github');
          const token = process.env.GITHUB_TOKEN;
          const octokit = new github.GitHub(token);
          const title = context.payload.issue.title.toLowerCase();
          
          let label = '';
          if (title.includes('t1')) {
            label = 'Tarea1';
          } else if (title.includes('proyecto')) {
            label = 'Proyecto';
          } else if (title.includes('etapa1')) {
            label = 'Etapa1';
          } else if (title.includes('etapa2')) {
            label = 'Etapa2';
          } else if (title.includes('etapa3')) {
            label = 'Etapa3';
          } else if (title.includes('contenido')) {
            label = 'Contenido';
          } else {
            label = 'other';
          }
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.issue.number,
            labels: [label]
          };
          await octokit.issues.addLabels(params);
          
